---
install_packages:
  - apt-transport-https
  - apt-utils
  - ca-certificates
  - code-oss # vscode
  - curl
  - git
  - jq

pip_packages:
  - ansible
  - keepercommander
  - molecule
  - molecule[docker,lint]
