---
# Use Ansible Galaxy to install dependencies
dependency:
  name: galaxy
  options:
    # Install required collections
    requirements-file: ../../requirements.yml

# Run molecule inside of a docker container
driver:
  name: docker

platforms:
  - name: kali-attack-box
    image: cisagov/docker-kali-ansible:latest
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
