---
name: Molecule Test
on:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    working-directory: "YOUR_NAME.PLAYBOOK_NAME"

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2004
          - debian11

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "YOUR_NAME.PLAYBOOK_NAME"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip3 install ansible molecule[docker] docker yamllint ansible-lint

      - name: Install galaxy dependencies
        run: ansible-galaxy install -r requirements.yaml

      - name: Run molecule tests
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
